public final class bm
{
  public static final String[] bn = { "健康游戏忠告", "抵制不良游戏，拒绝盗版游戏。", "注意自我保护，谨防受骗上当。", "适度游戏益脑，沉迷游戏伤身。", "合理安排时间，享受健康生活。" };
  public static final char[] c5 = { '-', '(', ')', '~', '"', '/', '&', '*', '@', '.', '?', '!', '#', '_', ',', ':', ';', '%', '=', '+', '<', '>', '\'', '\\', '[', ']', '{', '}', '。', 65292, '、', 65306, '“', '”', '’', 65311, 65281, '【', '】', '《', '》', '…' };
  public static final String[] cI = { "登　录", "注　册", "快速注册", "绑　定", "设　置", "帮　助", "关　于", "退　出", "游　客" };
  public static final String[] Y = { "快速注册", "登　录", "注　册", "绑　定", "设　置", "帮　助", "关　于", "退　出", "游　客" };
  public static final String[] bg = { "登　录", "快速注册", "注　册", "更多游戏", "网络设置", "帮　助", "关　于", "退　出", "点数专区" };
  public static final String[] aJ = { "高画质", "中画质", "低画质" };
  public static final String[] a2 = { "操作", "返回", "确定", "取消", "退出", "退　出", "查看详情", "比　较", "查　看", "错误", "接　受", "完　成", "查看物品", "编辑邮件", "发送邮件", "确定拍卖", "取回物品", "宝石雕琢", "选择道具", "雕琢说明", "放置道具", "装备开封", "开封说明", "重置道具", "原石合成", "合成说明" };
  public static final String[] jdField_byte = { a2[0], a2[1] };
  public static final String[] ap;
  public static final String[] aX;
  public static final String[] b3;
  public static final String[] dF;
  public static final int[] b7;
  public static final String[] S;
  public static final String[] w;
  public static final String[] ac;
  public static final String[] a6;
  public static final String[] jdField_goto;
  public static final String[] a4;
  public static final String[] e;
  public static final String[] aY;
  public static final String[] h;
  public static final String[] aW;
  public static final String[] bh;
  public static final String[] bd;
  public static final String[] aU;
  public static final String[] bp;
  public static final String[] cj;
  public static final String[] cb;
  public static final String[] m;
  public static final String[] dl;
  public static final String[] at;
  public static final String[] f;
  public static final String[] co;
  public static final String[] ak;
  public static final String[] c3;
  public static final String[] q;
  public static final String[] ch;
  public static final String[] c7;
  public static final String[] c6;
  public static final String[] c4;
  public static final String[] bU;
  public static final String[] ct;
  public static final String[] cr;
  public static final String[] cp;
  public static final String[] de;
  public static final String[] dd;
  public static final String[] dc;
  public static String[] au;
  public static int bY;
  public static int bP;
  public static int dx;
  public static int dw;
  public static int jdField_try;
  public static int dt;
  public static int cE;
  public static int cB;
  public static int cz;
  public static int aD;
  public static int aB;
  public static int A;
  public static int cQ;
  public static int H;
  public static int G;
  public static int bF;
  public static int E;
  public static int i;
  public static int af;
  public static int W;
  public static int ci;
  public static int y;
  public static int F;
  public static int jdField_else;
  public static int v;
  public static int aV;
  public static int cP;
  public static int an;
  public static int am;
  public static int o;
  public static int V;
  public static int bX;
  public static int a1;
  public static int aS;
  public static int cv;
  public static int cW;
  public static int cV;
  public static int cU;
  public static int a9;
  public static int a8;
  public static int a7;
  public static int a5;
  public static int aG;
  public static int bo;
  public static int ad;
  public static int ab;
  public static int b4;
  public static int ay;
  public static int ax;
  public static int aw;
  public static int aZ;
  public static int cF;
  public static int cD;
  public static int cA;
  public static int av;
  public static int cH;
  public static int jdField_void;
  public static int aR;
  public static int aP;
  public static final int[] cf;
  public static int bK;
  public static final int[][] O;
  public static final int[] c0;
  public static final String[] bH;
  public static final String[] Z;
  public static final String[] aO;
  public static final String[] bG;
  public static final String[] cn;
  public static final String[] ck;
  public static final String[] cu;
  public static final String[] bB;
  public static String[] bL;
  public static String[] c9;
  private static String[] bJ;
  public static String[] c1;
  public static String[] al;
  public static final int[] bR;
  public static long[] br;
  public static final short[] c;

  static
  {
    { "使　用", "查　看", "移　动", "整　理" }[4] = "丢　弃";
    { "装　备", "查　看", "移　动", "比　较", "整　理" }[5] = "丢　弃";
    new int[] { 3, 2, 3, 3 }[4] = 3;
    new int[] { 3, 2, 3, 2, 3 }[5] = 3;
    { "买入物品", a2[6] }[2] = a2[7];
    ap = new String[] { "物品查看", "兑换物品" };
    aX = new String[] { a2[6], "解除屏蔽", "添加黑名单" };
    new String[1][0] = "装　备";
    b3 = new String[] { "修改资料" };
    { "查看" }[1] = "使用";
    { "购　买", "查　看", "卸　下" }[3] = "比　较";
    dF = new String[] { "人物升级", "更换称号" };
    b7 = new int[] { 3, 2, 3 };
    new String[1][0] = "确定角色";
    new String[1][0] = "创建角色";
    S = new String[] { "聊　天" };
    { "更换风格", "开启增值" }[2] = "退出设置";
    { "更改连接" }[1] = "退出设置";
    w = new String[] { "放置", "重置", "锁定" };
    ac = new String[] { "查看", "取回", "重置", "锁定" };
    a6 = new String[] { "查看", "交易" };
    jdField_goto = new String[] { "选择物品", "邮寄物品", "查看" };
    a4 = new String[] { "查看", "整理" };
    e = new String[] { "整理" };
    aY = new String[] { "交易" };
    h = new String[] { "查看邮件", "删除邮件", "清空邮箱" };
    aW = new String[] { "人族", "仙族", "妖族", "魔族" };
    bh = new String[] { "剑客", "刺客", "道士", "医师", "幻术师", "暗巫" };
    bd = new String[] { "账号绑定可以提高您账号的安全性。绑定操作采用短信发送形式认证，如果您的账号已绑定则不可再次进行绑定。", "解除绑定可解除绑定的账号和绑定状态。本操作采用短信发送方式认证，必须使用原绑定的手机号发短信才能成功执行操作。", "如果您的账号已绑定，此操作可通过短信认证方式帮您找回遗忘的密码。只有原绑定的手机号发短信才能够成功执行此操作。" };
    aU = new String[] { "三界战乱千余年后，人类在仙族的帮助下，文明程度得到了极大的提升，人间一片空前的繁荣景象，仙族因一千五百年未曾斩却三尸，犯了杀戒，削弱了自己修炼的成果，要完成这场劫数才能继续修行，返本还元。", "三界战乱千余年来，妖魔从未停止过对力量与鲜血的渴望和追求，看似平静的妖魔之族却在酝酿着巨大的阴谋，它们暗中勾结那些心存邪念的人类与仙人，吸引他们走上邪路，慢慢积蓄力量，等待着机会来进行他们邪恶的计划。", "人族是最为庞大的种族，数量众多，占据着最多的大陆土地。人族天赋比较平庸，能力均衡。但正是因为没有什么特殊本领，所以人类总是非常努力地学习着所有事物，再加上超强的适应能力，勤能补拙的人族最终渐渐在世间挣出一片天。", "仙族是世界上最古老、最强大的种族，拥有无尽的寿命，曾是世界的最高管理者。仙族人拥有与生俱来的神奇法术，能够点石成金，呼风唤雨，在战斗中有着强大的杀伤力。美中不足的是天生体质柔弱，并不擅长物理系的攻击。", "妖族由天地间有灵性的异物经过千年修行进化而来。为得到本体，他们长期吸收日月天地的精华，直至化为人形。野外艰难的生存环境，让他们常常在死亡边缘徘徊。妖族数量不多，生性贪婪狡猾，从没有任何一个种族像妖族这么渴望力量。", "魔族是天地初化时与神一起诞生的最原始的种族，生性残忍暴虐，疯狂嗜杀，有着钢铁般强壮的体魄及超凡的怪力。天生愚钝的他们并不擅长法术，但极少数聪慧的魔族掌握了一种代代相传的诡异原始巫术。", "剑客是一个富有荣誉感的职业，他担负着斩奸除恶和保护队友的使命，剑客可以双手使用武器，剑、斧、锤、匕首、盾牌、巨型武器样样精通，可以装备重甲让剑客有更好的生存资本。剑客拥有各种武器华丽的招式，强健的体魄和崇高的精神。", "刺客是一个刺激而又富于挑战性的职业，华丽的技能，诡秘的行踪让刺客成为了一个谜一样的职业。刺客可以双手使用武器，剑，锤，匕首样样精通，可以装备皮甲让刺客行动更为灵活。神龙见首不见尾，万军之中取上将之首级如同探囊取物一般。", "道士是一个博大精深的职业，一般道士们都是闲散逍遥，闭门修行。相对纤弱的体质让道士只能装备布甲，武器也只有剑、匕首、法杖，副手可以选择，但是这丝毫不能影响道士的战斗力。奸邪面前他们会毫不留情地运用强大的法术一扫敌军，转瞬间，樯橹灰飞烟灭。", "医师是一个神圣的职业，救死扶伤是他们的天职，强大的治疗型法术可以保护队友。相对纤弱的体质让医师只能装备布甲，武器也只有锤、匕首、法杖可以选择，但是这丝毫不能影响医师在团队中的重要性。外表和善的医师也不是好惹的，一旦有人对医师出手，他们也有强力的法术制敌。", "幻术师是一个复合型职业，千变万化的变形法术，让他们精通各种体术、攻击法术和治疗法术。变化多端，神鬼莫测。幻术师可以双手使用武器，锤，法杖，斧，匕首，巨型武器样样精通，可以装备皮甲让幻术师行动更为灵活。", "暗巫是一个充满邪恶气息的职业，他们为了增强自身的实力，常年与阴暗的法术为伍。相对纤弱的体质让暗巫只能装备布甲，武器也只有剑、匕首、法杖可以选择，但是这丝毫不能影响暗巫的战斗力。出手辛辣，几近残忍，暗影瞬间就可以侵蚀敌人的灵魂。" };
    bp = new String[] { "人族和仙族结成的同盟...", "妖族与魔族联合所组的阵营...", "能力均衡,执着团结,拥有极强的适应力...", "古老而神秘的种族,灵感出众,卓尔不凡...", "具有灵性的异物,贪婪狡诈,极度渴望力量...", "原始种族,残忍暴虐,疯狂嗜杀...", "力量的象征,斩奸除恶,护卫队友...", "行踪诡秘,擅长偷袭,神龙见首不见尾...", "法术绚丽,攻强守弱,爆发力强大...", "心怀苍生,救死扶伤,韧性十足...", "精通各种技能,千变万化,神鬼莫测...", "技能邪恶偏激,出手残忍,侵蚀敌人的灵魂..." };
    cj = new String[] { "好友列表", a2[13], a2[14] };
    cb = new String[] { a2[13], a2[14] };
    m = new String[] { "放置物品", "重置物品", a2[14] };
    dl = new String[] { a2[12], a2[16], "重置物品", a2[14] };
    at = new String[] { a2[15], a2[16] };
    f = new String[] { "宝石镶嵌", a2[8] };
    co = new String[] { "查看宝石", "宝石替换" };
    ak = new String[] { "镶嵌" };
    c3 = new String[] { a2[6], "删除仇人", "添加仇人", "传送" };
    q = new String[] { a2[6], "删除仇人", "添加仇人" };
    ch = new String[] { "添加仇人" };
    { a2[12] }[1] = a2[21];
    new String[1][0] = a2[12];
    new String[1][0] = a2[17];
    c7 = new String[] { a2[18], a2[17], a2[19] };
    c6 = new String[] { a2[20], a2[6], a2[17], a2[19] };
    c4 = new String[] { a2[23], a2[6], a2[17], a2[19] };
    bU = new String[] { a2[20], a2[6], a2[21], a2[22] };
    { a2[18], a2[21] }[2] = a2[22];
    { a2[23], a2[6], a2[21] }[3] = a2[22];
    ct = new String[] { a2[18], a2[24], a2[25] };
    cr = new String[] { a2[23], a2[6], a2[24], a2[25] };
    cp = new String[] { a2[20], a2[6], a2[24], a2[25] };
    de = new String[] { a2[18], "宝石解除", "解除说明" };
    dd = new String[] { a2[23], a2[6], "宝石解除", "解除说明" };
    dc = new String[] { a2[20], a2[6], "宝石解除", "解除说明" };
    au = new String[] { "地图问题", "战斗问题", "道具问题", "人物问题", "其他问题" };
    bY = 4864570;
    bP = 4864570;
    dx = 7755053;
    dw = 14728078;
    jdField_try = 16575691;
    dt = 6045209;
    cE = 6045209;
    cB = 9333051;
    cz = 14728078;
    aD = 7755053;
    aB = 14728078;
    A = 16575691;
    cQ = 12490855;
    H = 7755053;
    G = 16637613;
    bF = 6045209;
    E = 16637613;
    i = 12490855;
    af = 6045209;
    W = 6045209;
    ci = 6045209;
    y = 14602158;
    F = 6045209;
    jdField_else = 6045209;
    v = 16637613;
    aV = 12490855;
    cP = 5450263;
    an = 6045209;
    am = 16637613;
    o = 4864570;
    V = 9333051;
    bX = 16637613;
    a1 = 13807232;
    aS = 6045209;
    cv = 14728078;
    cW = 6045209;
    cV = 9333051;
    cU = 14728078;
    a9 = 6045209;
    a8 = 6045209;
    a7 = 16637613;
    a5 = 6045209;
    aG = 16637613;
    bo = 4864570;
    ad = 14728078;
    ab = 5450263;
    b4 = 6045209;
    ay = 4864570;
    ax = 14728078;
    aw = 16575691;
    aZ = 6045209;
    cF = 14602158;
    cD = 6045209;
    cA = 14728078;
    av = 6045209;
    cH = 12490855;
    jdField_void = 0;
    aR = 6045209;
    aP = 12490855;
    cf = new int[] { 16711680, 16750080, 16776960, 65280 };
    bK = 16711424;
    new int[] { 8882055, 16776960 }[2] = 'ÿ';
    O = new int[][] { { 0, 11908533 }, { 18176, 48640 }, { 10329, 40191 }, { 5046385, 16711935 }, { 7356160, 16737792 }, { 7536640, 15007744 } };
    c0 = new int[] { 8224125, 16777215, 2192896, 1728767, 16711935, 16742400, 16711680 };
    bH = new String[] { "所有物品", "武器类", "防具类", "素材类", "消耗类", "其它" };
    Z = new String[] { "所有武器", "单手剑", "匕首", "法杖", "单手锤", "单手斧", "巨型武器", "副手" };
    aO = new String[] { "所有防具", "盾牌", "头部", "肩部", "胸部", "腿部", "腕部", "手部", "腰部", "脚部", "披风", "戒指", "项链", "法宝" };
    bG = new String[] { "所有素材", "布类", "皮类", "矿类", "草药类", "宝石类", "凝元材料" };
    cn = new String[] { "所有消耗品", "回复药水", "特效药水", "装备开封卷轴", "宝石雕琢符", "修补道具", "背包道具", "凝元符咒" };
    ck = new String[] { "所有宝石", "红色宝石", "黄色宝石", "蓝色宝石", "红宝石原石", "黄宝石原石", "蓝宝石原石" };
    cu = new String[] { "灰色品质", "白色品质", "绿色品质", "蓝色品质", "紫色品质", "橙色品质", "红色品质" };
    { "武器类", "重甲类", "皮甲类" }[3] = "布甲类";
    { "剑", "锤", "斧", "法杖", "匕首", "重型武器" }[6] = "副手";
    bB = new String[] { "", "游戏币:", "猛犸币:", "金元宝:", "银元宝:", "铜元宝:", "荣誉点数:", "竞技场点数:", "特殊需求:", "经验值:" };
    bL = new String[] { "游戏简介", "游戏规则", "操作说明" };
    c9 = new String[] { "千年时间转瞬即过，此时已到商周之时，天之浩劫又将降临这片饱经风霜的大地。在人间，昏君不思社稷，沉迷女色、荒废朝政、铸炮烙、杀忠臣、施苛政，百姓们食不果腹，流离失所。西伯侯之子周武王顺天意应民心，起兵讨伐暴君，封神大战就此展开…… ", "封神世界中分为两大阵营，每个阵营有两个种族，人仙和妖魔的这种对立关系使游戏产生了很多的玩法。游戏中共有剑客、刺客、道士、医师、幻术师和暗巫这6大职业，每个职业都有各自的特色技能和天赋，让游戏具备了出色的可玩性。围绕玩家为中心跟随剧情的深入逐步展开庞大系统脉络，你可以携手哪吒龙宫探险、伴随姜太公番溪垂钓、冒险国战火拼诸侯、组队好友得宝刷副，通过动态剧情过程享受跌宕起伏的真实乐趣，在这个奇幻的封神世界里，有你从未感受过的新奇体验。", "菜单界面\n\n方向键上：上移选择框\n方向键下：下移选择框\n方向键左：左移选择框\n方向键右：右移选择框\n左侧软键：确定\n右侧软键：返回\n\n 游戏中界面\n\n方向键上：向上移动\n方向键下：向下移动\n方向键左：向左移动\n方向键右：向右移动\n方向键中间：确认/攻击\n＃键：锁定\n＊键：聊天\n９键：切换快捷栏\n０键：切换画质\n左侧软键：根据画面提示确认相应操作\n右侧软键：根据画面提示确认相应操作 " };
    bJ = new String[] { "系统自动选择手机适配的网络类型。部分手机可能不支持，则请选择其他联网方式。", "手机中网络设置接入点写入CMWAP，用户名密码均无，代理服务器为10.0.0.172，端口80。", "手机中网络设置接入点写入CMNET，用户名密码均无。" };
    { "系统自动选择手机适配的网络类型。部分手机可能不支持，则请选择其他联网方式。", "手机中网络设置接入点写入UNIWAP。" }[2] = "手机中网络设置接入点写入UNINET。";
    c1 = new String[] { "帐户充值", "查询余额", "明细查询", "点数帮助" };
    al = (String[])bJ;
    bR = new int[] { 16776960, 16417256, 16750899, 52377, 65280, 39423, 16711680, 16711680, 8848254, 16777215, 8847615, 16716066 };
    br = new long[] { 0L, 0L, 0L, 0L, 0L, 0L };
    c = new short[] { 0, 5000, 10000, 5000, 5000, 5000 };
  }
}

/* Location:           C:\Users\ppz\Desktop\GOH_ALL2.jar
 * Qualified Name:     bm
 * JD-Core Version:    0.6.0
 */